steps:
  - name: 'python:3.9-slim'
    entrypoint: 'bash'
    args: [
      '-c',
      'pip install pyyaml google-cloud-compute && python ./applications/hcc/update_zone_region.py --project_id $PROJECT_ID'
    ]
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args: [
      '-c',
      'git status && git branch && git config user.email $_GITUSER_EMAIL && git config user.name $_GITUSER_NAME && git add . && if ! git diff-index --quiet HEAD --; then git commit -a -m "Update from Cloud Build" && git push origin ${BRANCH_NAME}'
    ]


options:
  logging: CLOUD_LOGGING_ONLY