steps:
- name: 'python:3.9-slim'
  entrypoint: 'bash'
  args: [
    '-c',
    'pip install pyyaml google-cloud-compute && python update_zone_region.py'
  ]
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args: [
    '-c',
    'git config user.email $_GITUSER_EMAIL && git config user.name $_GITUSER_NAME && git add. && git commit -m "Update from Cloud Build" && git push origin ${BRANCH_NAME}'
  ]

options:
  logging: CLOUD_LOGGING_ONLY