steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args: [ '-c', 'gcloud secrets versions access latest --secret=github-ssh-key > /root/.ssh/id_github' ]
    volumes:
    - name: 'ssh'
      path: /root/.ssh

  # Set up git with key and domain
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      chmod 600 /root/.ssh/id_github
      cat <<EOF >/root/.ssh/config
      Hostname github.com
      IdentityFile /root/.ssh/id_github
      EOF
      ssh-keyscan -t rsa github.com > /root/.ssh/known_hosts
    volumes:
    - name: 'ssh'
      path: /root/.ssh

  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
        git branch --set-upstream-to=origin/$BRANCH_NAME $BRANCH_NAME 
        git pull
        git checkout $BRANCH_NAME
        git pull origin $BRANCH_NAME

  - name: 'python:3.9-slim'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
        pip install pyyaml google-cloud-compute
        python ./applications/hcc/update_zone_region.py --project_id $PROJECT_ID
        touch ./applications/hcc/new_file.txt

  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
        git status
        git branch
        git config user.email ${_GITUSER_EMAIL}
        git config user.name "Yevet"
        git add ./applications/hcc/zone_to_region1.json
        git commit -m "Update from Cloud Build"
        git push origin ${BRANCH_NAME}
    volumes:
    - name: 'ssh'
      path: /root/.ssh

options:
  logging: CLOUD_LOGGING_ONLY